packages:
  - packages/*
  - examples/*

overrides:
  "esbuild@>=0.27.3 <0.28.1": 0.28.1

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
strictPeerDependencies: true
autoInstallPeers: false
engineStrict: true
allowBuilds:
  esbuild: true
